# -*- coding: utf-8 -*-
"""Another copy of Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4-c4xiJ0dQElivqBJsH0ZN5ZxxuQXvK
"""

#1. To write a pythin program to add two numbers enterd by user
a = int(input("Enter first no: "))
b = int(input("Enter second no: "))
sum = a+b
print(sum)

#2. write a python program to interchange the value of two variable
a = input("Enter first: ")
b = input("Enter second: ")
temp = a
a = b
b = temp
print(b)

#3.write a python program to find largest of three number using conditional statement
a = int(input("Enter first: "))
b = int(input("Enter second: "))
c = int(input("Enter third: "))
if a >c and a>b:
  print(a,"is largest")
elif b>c and b>a:
    print(b,"is largest")
else:
     print(c,"is largest")

#4. write a python program to check weather a given number is even or odd
num = int(input("Enter a number: "))
if(num%2==0):
  print(num,"is even number")
else:
    print(num, "is odd number")

#5.write a python program to determine whether a number is positive, negative or zero
num = int(input("Enter a number:"))
if num>0:
  print("Positive")
elif num<0:
    print("Negative")
else:
      print("zero")

#6.write a python program to check wether year is leap or not
year = int(input("Enter a year: "))
if year%4==0:
  print(year, "is a leap year")
else:
    print(year,"is not leap year")

#7 To write a python program to perform basic arthematic operation using operators
a = int(input("Enter first no: "))
b = int(input("Enter a second no:"))
print("Addition: ", a+b)
print("Subtraction: ",a-b)
print("Multiplication: ",a*b)
if b!=0:
  print("Division: ",a/b)
  print("Modulus: ",a%b)
  print("Floor Division: ",a//b)
else:
    print("Division is not possible")

"""8.To write a Python program to display the multiplication table of a given
number."""
num = int(input("Enter a number: "))
for i in range(1,11):
  print(num,"*",i,"=",num*i)

#9.To write a Python program to calculate the factorial of a number using a loop.
num = int(input("Enter a number:"))
for i in range(i,num+1):
  fact *= i
print("Factorial: ",fact)

#10.To write a Python program to find the sum of the first N natural numbers.
num = int(input("Enter a numbers: "))
sum = 0
for i in range(i,num+1):
  sum += i
print("Sum of first numbers: ",sum)

#11.To write a Python program to print numbers from 1 to N using a for loop.
num = int(input("Enter a number: "))
for i in range(1,num+1):
  print(i)

#12. To write a Python program to print numbers in reverse order from N to 1.
num = int(input("Enter a number: "))
for i in range(num,0,-1):
  print(i)

#13.To write a Python program to print all even numbers up to a given limit
num = int(input("Enter a number:"))
for i in range(2,num+1,2):
  print(i)

#14. To write a Python program to reverse the digits of a given number.
num =int(input("Enter a number:"))
rev = 0
while num>0:
    digit = num % 10
    rev = rev*10 + digit
    num = num // 10
print("Reverse: ", rev)

#15. To write a Python program to count the number of digits in a given integer.
num = int(input("Enter a number: "))
count = 0
while num>0:
  count += 1
  num = num // 10
print("number of digit count: ",count)

#16. To write a Python program to calculate the sum of digits of a given number.
num = int(input("Enter a number: "))
sum = 0
num = abs(num)
while num>0:
  digit = num % 10
  sum += digit
  num = num // 10
print("Sum of digit: ",sum)

#17 To write a Python program to check whether a given number is prime.
num = int(input("Enter a number:"))
if num >1:
  for i in range(2,num):
    if num%i==0:
      print(num, "is not prime")
      break
else:
      print(num, "is prime")

#18.To write a Python program to generate the Fibonacci series up to N terms.
n = int(input("Enter a number: "))
a,b = 0,1
print("Fibonacci series: ")
for i in range(n):
  print(a, end=" ")
  a,b=b, a+b

#19 To write a Python program to check whether a string is a palindrome.
text = input("Enter a text:")
if text == text[::1]:
  print("string is palindrome")
else:
   print("String is not palindrome")

#20.To write a Python program to check whether a given number is an Armstrong
#number.
n = int(input("Enter a number: "))
temp = n
sum = 0
digits = len(str(n))
while temp >0:
  digits = temp % 10
  sum += digit ** digit
  temp //= 10
  if sum == n:
    print(n,"is an armstrong number")
else:
      print(n, "is not strong armstrong")